services:
  database:
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_DB: "TodoApiDatabase"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "local_password"
    ports:
      - "5432:5432"